### ISSUE TITLE
Малко помощ

### ISSUE THREAD

**Issue by HristoManov91** [valeriayankova/Foodie#1]
Здравей.Видях ти кода и в моя проект имам нужда от такъв бутон като твоя за + ADD PRODUCT но нещо не успявам да си го имплементирам.Дали може да ми помогнеш аз имам нужда от 1 поле Product където от колекция User трябва да избере продукт и да го добави към продажба и ако има още продукти да натисне бутона и да добави и тях?Надявам се успях да обясня.Ако успееш да ми помогнеш ще съм ти много благодарен :)
https://github.com/HristoManov91/Celio/tree/main/SellersResults

**Comment by valeriayankova** [comment]
Здрасти, ще погледна утре, че сега не съм на компютъра. При мен проблемът беше в таймлийф темплейта и jquery-то. Направо тоя проблем ми разказа играта, така че те разбирам напълно 😂

**Comment by HristoManov91** [comment]
Да няма проблем не бързам.То при мен като цяло не знаех как да го
направя,защото нито html съм карал нито js и ми е тормоз.Хареса ми ти как
си го направила само ако може с някакви леки промени да ми кажеш как да го
направя въпросният продукт да не се въвежда а да се избира от колекция
продукти като съм подал към модела и накрая при събмит да ми върне лист с
техните имена примерно.Благодаря ти

На чт, 11.11.2021 г. в 22:02 ч. Valeria Yankova ***@***.***>
написа:

> Здрасти, ще погледна утре, че сега не съм на компютъра. При мен проблемът
> беше в таймлийф темплейта и jquery-то. Направо тоя проблем ми разказа
> играта, така че те разбирам напълно 😂
>
> Sent from my iPhone
>

**Comment by HristoManov91** [comment]
Здравей само да те подсетя като може да погледнеш :)
